modLoader="javafml" #mandatory
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Aelpecyem/Elementaristics-1.15.2/issues" #optional
[[mods]]
modId="elementaristics"
version="${file.jarVersion}"
displayName="Elementaristics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/elementaristics"
logoFile="elementaristics_logo.png"
credits="Cybercat5555 for amazing deity models, the entire discord of Elementaristics, special thanks to Morinor and gunroot2525"
authors="Aelpecyem, Cybercat5555"
description='''
The Elementaristics are the arts of dancing to Nothingness and beyond; this includes ascension, alchemy and cults.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.elementaristics]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
